<a href="https://colab.research.google.com/github/pacho9090/hyperblog/blob/master/Actividad2_AprendizajeAutomatico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**ACTIVIDAD 2 - Métodos de Aprendizaje Automático**

GRUPO 5
Diaz Cuesta, Yeffer
Valbuena Acosta, Carlos
Pizarro Rivera, Francisco

In [1]:
## Importación de librerias

import pandas as pd
import seaborn as sb
import sklearn as sk

In [6]:
# Cargue de datos

data = pd.read_excel("Dermato_Data.xlsx")
data

,1_erythema,2_scaling,3_definite borders,4_itching,5_koebner phenomenon,6_polygonal papules,7_follicular papules,8_oral mucosal involvement,9_knee and elbow involvement,10_scalp involvement,...,26_disappearance of the granular layer,27_vacuolisation and damage of basal layer,28_spongiosis,29_saw-tooth appearance of retes,30_follicular horn plug,31_perifollicular parakeratosis,32_inflammatory monoluclear inflitrate,33_band-like infiltrate,34_Age (linear),35_ID
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,55,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,8,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,26,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,40,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,45,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2,1,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,2,0,25,4
362,3,2,1,0,1,0,0,0,0,0,...,1,0,1,0,0,0,2,0,36,4
363,3,2,2,2,3,2,0,2,0,0,...,0,3,0,3,0,0,2,3,28,3
364,2,1,3,1,2,3,0,2,0,0,...,0,2,0,1,0,0,2,3,50,3
365,3,2,2,0,0,0,0,0,3,3,...,2,0,0,0,0,0,3,0,35,1